### ISSUE TITLE
silent failure if token is bad

### ISSUE THREAD

**Issue by markstos** [kelonye/winston-logentries-simple#1]
If the LogEntries token is bad, no error is emitted and logging will appear to work, but actually the logs will be thrown away. 

This can tested by copy/pasting the "Usage" example into a file and running it (with the placeholder token still in place).

**Comment by kelonye** [comment]
Seems logentries fails silently .. :(

**Comment by markstos** [comment]
It appears you are using a combination of host name and port which are not recommended. 

[These docs](https://logentries.com/doc/input-token/) show that connecting to 'data.longentries.com' is supposed on ports `80`, `512` and `10000`, and that you can connect to `api.logentries.com` on port `20000`. However this project combines the port number of `10000` from the former list with the hostname of `api.logentries.com` from the latter list.

**Comment by kelonye** [comment]
Awesome!

![](https://www.evernote.com/shard/s138/sh/3ce2d715-f877-49d9-8266-712732208f05/8ca97b8e91163e58/res/26406c8a-12c4-443a-82f0-4539a9f3cc43/skitch.png?resizeSmall&width=832)
